version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Maps port 4000 in the container to port 4000 on the host
    environment:
      - PORT=5173
    volumes:
      - .:/app
